# Generated by Django 4.0.2 on 2022-05-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='dueDate',
            field=models.DateTimeField(verbose_name='date due'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
