# Generated by Django 4.0.2 on 2022-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_name_alter_assignment_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
