# Generated by Django 4.0.2 on 2022-05-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='grade',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
