# Generated by Django 4.0.2 on 2022-05-26 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='assignmentClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
    ]
